# Generated by Django 3.0 on 2025-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdatamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=300)),
                ('DOB', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=300)),
                ('PAN', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='patientsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
            ],
        ),
    ]
